### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by krauthaufen** [aardvark-platform/node-shared-mem#1]
Linux support via shm_open

**Comment by haraldsteinlechner** [comment]
should be done in a9e838df8ea83d334c7f8e054692ea8fcaa95382 (just checking in media)

**Comment by haraldsteinlechner** [comment]
not sure, think this was a fail!
``` 0: WARNING: [2997:0814/215619.210308:INFO:CONSOLE(164)] "Unable to load preload script: /home/hs/.config/Aardium/x64/1.0.19/tools/resources/app/preload.js", source: /home/hs/.config/Aardium/x64/1.0.19/tools/resources/electron.asar/renderer/init.js (164)
 0: WARNING: [2997:0814/215619.211634:INFO:CONSOLE(165)] "Error: /home/hs/.config/Aardium/x64/1.0.19/tools/resources/app/node_modules/node-shared-mem/build/Release/node_shared_mem.node: invalid ELF header
 0: WARNING:     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
 0: WARNING:     at Object.Module._extensions..node (module.js:671:18)
 0: WARNING:     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
 0: WARNING:     at Module.load (module.js:561:32)
 0: WARNING:     at tryModuleLoad (module.js:504:12)
 0: WARNING:     at Function.Module._load (module.js:496:3)
 0: WARNING:     at Module.require (module.js:586:17)
 0: WARNING:     at require (internal/module.js:11:18)
 0: WARNING:     at bindings (/home/hs/.config/Aardium/x64/1.0.19/tools/resources/app/node_modules/bindings/bindings.js:76:44)
 0: WARNING:     at Object.<anonymous> (/home/hs/.config/Aardium/x64/1.0.19/tools/resources/app/node_modules/node-shared-mem/addon.js:1:187)", source: /home/hs/.config/Aardium/x64/1.0.19/tools/resources/electron.asar/renderer/init.js (165)
```

**Comment by krauthaufen** [comment]
we had that running a year ago didn't we?
